***MAGPANTAY, NINO JANDEL C***

***BSCS-3B***

***MR. BERNARDINO***

Multiple Linear Regression

# **1. Import Libraries**

In [1]:
import pandas as pd #Data Manipulation
import numpy as np #Mathematical operation
import matplotlib.pyplot as plt #Data Vizualization
from sklearn.model_selection import train_test_split #Training Data/Data Modeling
from sklearn.linear_model import LinearRegression #Training Data/Data Modeling
from sklearn.metrics import mean_squared_error #Training Data/Data Modeling

# **2. Creating a Synthetic Dataset**

In [3]:
np.random.seed() #For Reproducibility
x = np.random.rand(100,3) #
y = x[:,0] * 150000 + x[:, 1] * 100000 + x[:, 2] * 50000 + 50000


# **3. Converting to a DataFrame**

In [ ]:
data = pd.DataFrame(x, columns=['Size','Bedrooms','Age'])
data['Price'] = y

data.head()

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

data.head()

Size  Bedrooms       Age          Price
0  0.887886  0.197154  0.882581  247027.345306
1  0.908184  0.397952  0.177372  234891.362029
2  0.531635  0.462221  0.639075  207921.081020
3  0.336530  0.618803  0.081895  166454.562900
4  0.210298  0.901952  0.027848  173132.359141

# **4. Initializing the Model**

In [ ]:
model = LinearRegression()

# **5. Fitting the Model**

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

# **6. Making Predictions**

In [ ]:
y_predict =model.predict(x_test)
print(x_test)
print (y_predict)

[[0.89612021 0.55814881 0.57513238]
 [0.79120307 0.3930881  0.07080833]
 [0.36696567 0.97331134 0.99125429]
 [0.3879009  0.36856308 0.41310192]
 [0.91002988 0.33657613 0.05292718]
 [0.63607688 0.67555997 0.56842564]
 [0.20823898 0.85625723 0.78670385]
 [0.85190921 0.57265964 0.27698686]
 [0.76475215 0.31029747 0.90001971]
 [0.88788579 0.19715448 0.88258057]
 [0.19342592 0.76418225 0.89270739]
 [0.1084699  0.56605563 0.81400551]
 [0.56325098 0.92525568 0.52293703]
 [0.8395012  0.41731966 0.14712085]
 [0.10141215 0.48442407 0.6230034 ]
 [0.21029801 0.90195244 0.02784827]
 [0.55955747 0.07834838 0.66466697]
 [0.0762042  0.56794667 0.49473418]
 [0.30638125 0.68827049 0.96610465]
 [0.18309271 0.15930849 0.86082438]]
[268989.53067595 211529.68758086 251938.69917168 165696.53779991
 222808.45432655 241388.81044257 206196.76256517 248901.68826735
 240743.55478711 247027.345306   200067.48282805 163576.3235638
 253160.06585521 225013.18807925 144804.39985616 173132.3591409
 175001.80650055 1429

# **7. Calculating the Mean Squred Error**

In [ ]:
mse = mean_squared_error(y_test,y_predict)
print(f"Mean Squarred Error: {mse}")

Mean Squarred Error: 8.470329472543003e-22


# **8. Predicting The Price Of A New House**

In [ ]:
new_house = [(0.5,2,10)]
predicted_price = model.predict(new_house)
print(f"Predicted: {predicted_price[0]}")

Predicted: 825000.0
